/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import Clases.Cliente;
import Clases.Encuesta;
import javax.swing.JOptionPane;

/**
 *
 * @author maxi
 */
public class formularioCliente extends javax.swing.JFrame {

    /**
     * Creates new form formularioCliente
     */
    public formularioCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        INnombre = new javax.swing.JTextField();
        TXTnombre = new javax.swing.JLabel();
        TXTapellido = new javax.swing.JLabel();
        INapellido = new javax.swing.JTextField();
        TXTcliente = new javax.swing.JLabel();
        INcliente = new javax.swing.JTextField();
        BTNresultados = new javax.swing.JButton();
        TXTnivelatencion = new javax.swing.JLabel();
        TXTnivelresolucion = new javax.swing.JLabel();
        TXTnivelrecomendacion = new javax.swing.JLabel();
        INnresolucion = new javax.swing.JSlider();
        INnrecomendacion = new javax.swing.JSlider();
        INnatencion = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        INnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INnombreActionPerformed(evt);
            }
        });

        TXTnombre.setText("Nombre");

        TXTapellido.setText("Apellido");

        TXTcliente.setText("Numero de cliente");

        BTNresultados.setText("Ver Resultados");
        BTNresultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNresultadosActionPerformed(evt);
            }
        });

        TXTnivelatencion.setText("Nivel de Atencion");

        TXTnivelresolucion.setText("Nivel de Resolucion");

        TXTnivelrecomendacion.setText("Nivel de Recomendacion");

        INnresolucion.setMajorTickSpacing(1);
        INnresolucion.setMaximum(10);
        INnresolucion.setPaintLabels(true);

        INnrecomendacion.setMajorTickSpacing(1);
        INnrecomendacion.setMaximum(10);
        INnrecomendacion.setPaintLabels(true);

        INnatencion.setMajorTickSpacing(1);
        INnatencion.setMaximum(10);
        INnatencion.setPaintLabels(true);
        INnatencion.setToolTipText("");
        INnatencion.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(INcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103)
                                .addComponent(INnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addComponent(INapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TXTcliente)
                                .addGap(91, 91, 91)
                                .addComponent(TXTnombre)
                                .addGap(141, 141, 141)
                                .addComponent(TXTapellido)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(TXTnivelatencion)
                                .addGap(149, 149, 149)
                                .addComponent(TXTnivelresolucion))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(INnatencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BTNresultados)
                                    .addComponent(INnresolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTnivelrecomendacion)
                            .addComponent(INnrecomendacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(29, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTcliente)
                    .addComponent(TXTnombre)
                    .addComponent(TXTapellido))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(INcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(INapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(INnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTnivelatencion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTnivelresolucion)
                    .addComponent(TXTnivelrecomendacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INnatencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(INnresolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(INnrecomendacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(BTNresultados)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void INnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INnombreActionPerformed

    private void BTNresultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNresultadosActionPerformed

       boolean validado=true;
       int contador=0;

       Cliente persona1=new Cliente();
       
        /*
        valido entradas
        */
        
        String numdecliente=INcliente.getText();
        
        if (persona1.esNumerico(numdecliente)== false){     //si no es numero
                JOptionPane.showMessageDialog(null,"Numero de cliente TIENE que ser numerico");
                validado=false;
        }else{
            int numcliente = Integer.parseInt(numdecliente);
            persona1.setNumdecliente(numcliente);
            contador++; //1
        }

        String nombre=INnombre.getText();
        
        if (persona1.estaVacio(nombre)== true){
            JOptionPane.showMessageDialog(null,"El nombre NO puede estar vacio");
            validado=false;
        }else{
            persona1.setNombre(nombre);
            contador++; //2
        }
        
        String apellido=INapellido.getText();
            
        if (persona1.estaVacio(apellido) == true){
            JOptionPane.showMessageDialog(null,"El apellido NO puede estar vacio");
            validado=false;
        }else{
            persona1.setApellido(apellido);
            contador++; //3
        }

        Encuesta encuesta1= new Encuesta(persona1.getNumdecliente(),persona1.getNombre(),persona1.getApellido());

        int natencion= INnatencion.getValue();
        
        encuesta1.setNivelAtencion(natencion);
        
        int nresolucion= INnresolucion.getValue();
        
        encuesta1.setNivelResolucion(nresolucion);

        int nrecomendacion= INnrecomendacion.getValue();
        
        encuesta1.setNivelRecomendacion(nrecomendacion);
        
        float promedio=encuesta1.Promedio(natencion, nresolucion, nrecomendacion);
        
        
        if ((validado == true) && (contador == 3)){
            
            resultado re=new resultado();
            re.setInfo(natencion, nresolucion, nrecomendacion,promedio);
            this.dispose();
            re.setVisible(true);

        }else {

            formularioCliente fc = new formularioCliente();   //instancio el formulario nuevamente
            this.dispose();     
            fc.setVisible(true);
            contador=0;
            validado=false;

        }
        
  

    }//GEN-LAST:event_BTNresultadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formularioCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNresultados;
    private javax.swing.JTextField INapellido;
    private javax.swing.JTextField INcliente;
    private javax.swing.JSlider INnatencion;
    private javax.swing.JTextField INnombre;
    private javax.swing.JSlider INnrecomendacion;
    private javax.swing.JSlider INnresolucion;
    private javax.swing.JLabel TXTapellido;
    private javax.swing.JLabel TXTcliente;
    private javax.swing.JLabel TXTnivelatencion;
    private javax.swing.JLabel TXTnivelrecomendacion;
    private javax.swing.JLabel TXTnivelresolucion;
    private javax.swing.JLabel TXTnombre;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    // End of variables declaration//GEN-END:variables
}
